//Don't write js here, just call other .js files. This syntax is unique to Prepros, but you could use any build tool to compile js. jQuery is called using CDN, see index.html as an example.

// @prepros-prepend "bootstrap/affix.js"
// @prepros-prepend "bootstrap/transition.js"
// @prepros-prepend "bootstrap/tooltip.js"
// @prepros-prepend "bootstrap/alert.js"
// @prepros-prepend "bootstrap/button.js"
// @prepros-prepend "bootstrap/carousel.js"
// @prepros-prepend "bootstrap/collapse.js"
// @prepros-prepend "bootstrap/dropdown.js"
// @prepros-prepend "bootstrap/modal.js"
// @prepros-prepend "bootstrap/popover.js"
// @prepros-prepend "bootstrap/scrollspy.js"
// @prepros-prepend "bootstrap/tab.js"
// @prepros-prepend "main.js"
